### ISSUE TITLE
Add prettier and prettier-fix script for staged changes

### ISSUE THREAD

**Issue by sanchitgupta001** [sam0hack/cache-checker#27]
For code formatting, can we add prettier as dev dependency.
Also, we can add prettier-fix script for the staged changes.

If it seems appropriate, I can add the same.

**Comment by sam0hack** [comment]
sure let's do it :+1:

**Comment by sanchitgupta001** [comment]
@sam0hack Please assign it to me then

**Comment by sam0hack** [comment]
done!

**Comment by sanchitgupta001** [comment]
https://github.com/sam0hack/cache-checker/pull/29
PR for the same

**Comment by sanchitgupta001** [comment]
https://github.com/sam0hack/cache-checker/pull/32
Have added prettier-fix as git pre-commit hook

**Comment by sanchitgupta001** [comment]
@sam0hack can we add hacktobefest label to this issue as well ?

**Comment by sanchitgupta001** [comment]
@sam0hack can you add hacktoberfest label to this as well ?

Also, I have added prettier-fix as git pre-commit hook
https://github.com/sam0hack/cache-checker/pull/32 Pull request for the same
